---
- name: remove elastic user and homedir
  user:
    name: elastic
    state: absent
    remove: yes

- name: remove elastic group
  group:
    name: elastic
    state: absent

- name: remove unneeded packages
  zypper:
    name: "{{ item }}"
    state: absent
  with_items:
    - htop
    - sshpass
    - zsh
    - git
    - ansible
    - puppet
    - ruby
    - cvs
    - rcs
    - python-argparse
    - git-email
    - git-gui
    - gitk
    - git-svn
    - git-core
    - python-setuptools

- name: remove unneeded dirs and files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/sudoers.d/elastic
    - /root/ruby-2.1.8.tar.gz
    - /root/.subversion
    - /root/.gem
    - /root/inst-sys
    - /usr/local/bin
    - /usr/local/doc/*
    - /usr/local/games/*
    - /usr/local/include/*
    - /usr/local/lib/*
    - /usr/local/lib64/*
    - /usr/local/man/man*/*
    - /usr/local/share/*
    - /usr/local/src/*
    - /etc/init.d/vboxadd-x11

- name: "remove old repositories of sles11"
  zypper_repository:
    name: "{{ item }}"
    state: absent
  when: ansible_os_family == 'Suse' and ansible_distribution_major_version|int == 11
  with_items:
    - sles11-dvd2
    - sles11-sdk-dvd2

- name: "add correct sles11-repos"
  zypper_repository:
    name: "{{ item.name }}"
    repo: "{{ item.repo }}"
    runrefresh: yes
    state: present
  when: ansible_os_family == 'Suse' and ansible_distribution_major_version|int == 11
  with_items:
    - { name: 'sles11-sdk-dvd1', repo: 'ftp://ftp.uni-halle.de/suse/SLES.11/SLES11-SP4-SDK/' }
    - { name: 'sles11-dvd1', repo: 'ftp://ftp.uni-halle.de/suse/SLES.11/SLES11-SP4/' }
